# Configuration settings for the file manager application.
# This file contains constants and default values used throughout the application.
# It is recommended to keep this file in the same directory as the main application script.

# Constants
FILE_TYPES_TO_KEEP = [
    "jpg",
    "jpeg",
    "png",
    "gif",
    "tif",
    "tiff",
    "bmp",
    "webp",
    "webm",
    "svg",
    "dng",
    "pdf",
    "mp4",
    "mov",
    "mp3",
    "sql",
    "txt",
    "pptx",
    "xlsx",
    "docx",
    "xls",
    "rtf",
    "zip",
    "iso",
    "csv",
    "log",
    "rar",
    "md",
    "tar",
    "ai",
    "ics",
    "db",
    "json",
    "xml",
    "html",
    "htm",
    "py",
    "js",
    "ts",
    "java",
    "c",
    "xcf",
    "cpp",
    "cs",
    "go",
    "rb",
    "php",
    "sh",
    "bat",
    "ps1",
    "yaml",
    "yml",
    "ini",
    "cfg",
    "conf",
    "xmind",
    "vcf",
]
FOLDERS_TO_REMOVE = ["pip", "node_modules"]
DEFAULT_SRC_PATH = "C:/Users/terti/OneDrive/bck"
DEFAULT_DST_PATH = "C:/Users/terti/OneDrive"
DEFAULT_LOG_PATH = "C:/tmp/file_manager.log"
